### ISSUE TITLE
Do not require the most recent versions of dependencies

### ISSUE THREAD

**Issue by pietsch** [LibreCat/MODS-Record#2]
Requiring the most recent versions of dependencies as you do in `cpanfile` makes in very difficult to package this module for operating systems.

- Moo: For instance, requiring the latest Moo means that I cannot package this module for Debian. The upcoming stable release of Debian (jessie) has Moo 1.00600. The tests in this module run fine with Moo 1.00600.
- Carp: Also, requiring version 1.3301 of the core package Carp means that this module only works with Perl 5.19.11 or newer (see `corelist Carp 1.3301`). This is not what we want, is it?
- JSON: you require 2.90, but only 2.61 is in Debian testing (jessie).
- XML::Parser: you require 2.44, but only 2.41 is in Debian testing (jessie).

Ideally, when creating Debian packages, I would like them to work with the current stable (wheezy) and old stable (squeeze) versions as well, so please try not to require more recent versions than you really need.

**Comment by phochste** [comment]
Where can I find a listing of Perl packages available in  wheezy? I'm a bit lost here we have CentOS here

**Comment by pietsch** [comment]
Luckily, everything is online: https://packages.debian.org/stable/perl/

C:
